### ISSUE TITLE
AADSTS70021: No matching federated identity record found for presented assertion.

### ISSUE THREAD

**Issue by ilmax** [Azure/azure-workload-identity#340]
**Describe the bug**
After following the documentation on how to setup the azure workload identity, I'm getting this error consistently. I've double checked the application id, the issuer and everything else but I am clearly missing something here because even following the quick-start steps I get the same result.

**Steps To Reproduce**
Follow the quick-start steps

**Expected behavior**
Application can read secret from the azure keyvault

**Logs**
```
token_credential.go:70] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com//{tenant-id}//oauth2/v2.0/token)(POST) error: reply status code was 400:\n{\"error\":\"invalid_request\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://oidc.prod-aks.azure.com/XXXXXX/'. Assertion Subject: 'system:serviceaccount:default:workload-identity-sa'. Assertion Audience: 'api://AzureADTokenExchange'.\\r\\nTrace ID: b0f62116-10b6-4a73-bdb2-281524404e00\\r\\nCorrelation ID: 4a42e576-85bc-46ae-b7e3-b52cb8958917\\r\\nTimestamp: 2022-01-20 22:54:42Z\",\"error_codes\":[70021],\"timestamp\":\"2022-01-20 22:54:42Z\",\"trace_id\":\"b0f62116-10b6-4a73-bdb2-281524404e00\",\"correlation_id\":\"4a42e576-85bc-46ae-b7e3-b52cb8958917\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}"
E0120 22:55:12.472912       1 token_credential.go:70] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token)(POST) error: reply status code was 400:\n{\"error\":\"invalid_request\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://oidc.prod-aks.azure.com/XXXXXX/'. Assertion Subject: 'system:serviceaccount:default:workload-identity-sa'. Assertion Audience: 'api://AzureADTokenExchange'.\\r\\nTrace ID: 8f29172d-bf0d-4165-9d86-816665612d00\\r\\nCorrelation ID: 472f3de0-666f-411e-8d4c-cd46b6d6db26\\r\\nTimestamp: 2022-01-20 22:55:12Z\",\"error_codes\":[70021],\"timestamp\":\"2022-01-20 22:55:12Z\",\"trace_id\":\"8f29172d-bf0d-4165-9d86-816665612d00\",\"correlation_id\":\"472f3de0-666f-411e-8d4c-cd46b6d6db26\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}"
```

**Environment**

- Kubernetes version (use `kubectl version`): 1.20.9
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: azwi
- Network plugin and version (if this is a network-related bug): Kubenet
- Others:

**Additional context**
Following the troubleshooting steps in the documentation doesn't seems to help, the logs for the pods in the azure-workload-identity-system namespace doesn't seems to get updated, no matter what I'm doing, here's the content of the log:

```
I0120 15:13:26.106278       1 deleg.go:130] cert-rotation "msg"="no cert refresh needed"  
I0120 15:15:07.879809       1 deleg.go:130] cert-rotation "msg"="certs are ready in /certs"  
I0120 15:15:07.879862       1 deleg.go:130] cert-rotation "msg"="CA certs are injected to webhooks"  
I0120 15:15:07.879880       1 deleg.go:130] entrypoint "msg"="setting up webhook server"  
I0120 15:15:07.879930       1 deleg.go:130] entrypoint "msg"="registering webhook to the webhook server"  
I0120 15:15:07.880045       1 server.go:139] controller-runtime/webhook "msg"="registering webhook" "path"="/mutate-v1-pod" 
I0120 15:15:07.880112       1 server.go:207] controller-runtime/webhook/webhooks "msg"="starting webhook server"  
I0120 15:15:07.880302       1 deleg.go:130] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I0120 15:15:07.880432       1 deleg.go:130] controller-runtime/webhook "msg"="serving webhook server"  "host"="" "port"=9443
I0120 15:15:07.880537       1 deleg.go:130] controller-runtime/certwatcher "msg"="Starting certificate watcher"  
I0120 15:13:24.099630       1 rotator.go:665] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0120 15:15:02.407590       1 deleg.go:130] cert-rotation "msg"="certs are ready in /certs"  
I0120 15:15:02.407640       1 deleg.go:130] cert-rotation "msg"="CA certs are injected to webhooks"  
I0120 15:15:02.407655       1 deleg.go:130] entrypoint "msg"="setting up webhook server"  
I0120 15:15:02.407702       1 deleg.go:130] entrypoint "msg"="registering webhook to the webhook server"  
I0120 15:15:02.407842       1 server.go:139] controller-runtime/webhook "msg"="registering webhook" "path"="/mutate-v1-pod" 
I0120 15:15:02.407909       1 server.go:207] controller-runtime/webhook/webhooks "msg"="starting webhook server"  
I0120 15:15:02.408103       1 deleg.go:130] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I0120 15:15:02.408212       1 deleg.go:130] controller-runtime/webhook "msg"="serving webhook server"  "host"="" "port"=9443
I0120 15:15:02.408314       1 deleg.go:130] controller-runtime/certwatcher "msg"="Starting certificate watcher"  
```

Is there something else I can do to troubleshoot the issue?

**Comment by ilmax** [comment]
I found the solution, it was the wrong issuer uri in the federated credentials, was missing a trailing /.
In order to debug this I ssh into the container and checked the JWT token via a `cat /var/run/secrets/tokens/azure-identity-token` and decoded and compared iss, aud and sub to the federated credential, leaving this here just in case anyone run into the same issue.

Issue is solved, closing this!

**Comment by kmasulisNetrix** [comment]
> I found the solution, it was the wrong issuer uri in the federated credentials, was missing a trailing /. In order to debug this I ssh into the container and checked the JWT token via a `cat /var/run/secrets/tokens/azure-identity-token` and decoded and compared iss, aud and sub to the federated credential, leaving this here just in case anyone run into the same issue.
> 
> Issue is solved, closing this!

I have tried this and still getting the error.  My issuer is "https://token.actions.githubusercontent.com//".
